### ISSUE TITLE
checking the condition number for svd

### ISSUE THREAD

**Issue by moshanATucsd** [nkolot/GraphCMR#10]
Hi, in the following code in GraphCMR/models/smpl_param_regressor.py, I am wondering whether we should check the condition number of A[i] before using svd? If the condition number of A[i] is close to 1, then backpropagation through svd might give nan values. 

```
def batch_svd(A):
    """Wrapper around torch.svd that works when the input is a batch of matrices."""
    U_list = []
    S_list = []
    V_list = []
    for i in range(A.shape[0]):
        U, S, V = torch.svd(A[i])
        U_list.append(U)
        S_list.append(S)
        V_list.append(V)
    U = torch.stack(U_list, dim=0)
    S = torch.stack(S_list, dim=0)
    V = torch.stack(V_list, dim=0)
    return U, S, V
```

**Comment by nkolot** [comment]
Yes I am aware of that. I have never seen any issues during training though.

**Comment by moshanATucsd** [comment]
Got it!
