### ISSUE TITLE
 hyper-params differ from those in the paper?

### ISSUE THREAD

**Issue by Maqingyang** [nkolot/GraphCMR#11]
In README it said that when choosing training hyper-params,  the default values are the ones used to train the models in the paper. 
However I found there are some differences between code default settings and those in the paper.

**--batch_size** 
    In default settings it is **_2_**. However , it is **_16_** in the paper.

**--lr** 
   In default settings it is **_2.4e-4_**. However, it is _**3e-4**_ in the paper.

**--num__epochs & --dataset** 
    In default settings you use **_50_** epochs and **_'itw'_** option which excludes Human3.6M dataset. However, in the paper you talked about a _two-stage_ training strategy.

**--rot_factor & --noise_factor & --scale_factor** 
    In default settings these options are **_used_,** but they are **_not mentioned_** in the paper.

I feel a little confused about which hyper-params set to choose. Could you help me here to better reproduce the results in the paper?

**Comment by nkolot** [comment]
For the hyperparameters you should use the values reported in the paper.
Also I recommend using data augmentation.

**Comment by yuxwind** [comment]
Hi Nikos,

Thanks for sharing your great job in the paper. I have the same confusion with --num__epochs & --dataset parameter as @Maqingyang. 

You mentioned that 

_"Training with data only from Human3.6M lasts for 10 epochs, while mixed training with data from Human3.6M and UP3D requires training for 25 epochs, because of the greater
image diversity"_

Do you mean you train 10 epochs when only on Human3.6M, and 25 epochs when on the mixed datasets with Human3.6M and UP3D? As in the default setting, you train 50 epochs on the mixed datasets with Human3.6M, UP3D, MPII, COCO, LSP. 

I might have a misunderstanding. It would be great if you could prove a more detailed explanation of your training strategy. Thanks!

**Comment by yuxwind** [comment]
> In README it said that when choosing training hyper-params, the default values are the ones used to train the models in the paper.
> However I found there are some differences between code default settings and those in the paper.
> 
> **--batch_size**
> In default settings it is **_2_**. However , it is **_16_** in the paper.
> 
> **--lr**
> In default settings it is **_2.4e-4_**. However, it is _**3e-4**_ in the paper.
> 
> **--num__epochs & --dataset**
> In default settings you use **_50_** epochs and **_'itw'_** option which excludes Human3.6M dataset. However, in the paper you talked about a _two-stage_ training strategy.
> 
> **--rot_factor & --noise_factor & --scale_factor**
> In default settings these options are **_used_,** but they are **_not mentioned_** in the paper.
> 
> I feel a little confused about which hyper-params set to choose. Could you help me here to better reproduce the results in the paper?

@Maqingyang Do you have any luck to figure out the proper parameter settings? Thanks!

**Comment by Maqingyang** [comment]
In fact I follow the paper's hyperparameter, but have't produce the scores the paper reported. Maybe the author could provide more details about training process and help to reproduce the scores. If you have reproduce the scores, please let me know, thanks! @yuxwind

**Comment by nkolot** [comment]
What are the scores you are getting?

**Comment by Maqingyang** [comment]
h36m-p1
MPJPE (NonParam): 139.3199177315659
Reconstruction Error (NonParam): 59.20808539927326
MPJPE (Param): 95.11126801614222
Reconstruction Error (Param): 56.31886701213058

h36m-p2
MPJPE (NonParam): 137.5788705966492
Reconstruction Error (NonParam): 56.405959431544595
MPJPE (Param): 91.3564615155462
Reconstruction Error (Param): 53.2527044260017
