### ISSUE TITLE
Train the graph adjacency matrix?

### ISSUE THREAD

**Issue by sheoranhimansh** [nkolot/GraphCMR#14]
Hi, 
In your code, you are loading the precomputed graph adjacency matrix and upsampling/downsampling matrices. Is there a way to train it?
Can you please tell how did you compute both of them?

**Comment by nkolot** [comment]
The upsampling and downsampling were precomputed following the same procedure as in [here](https://github.com/anuragranj/coma). For the graph adjacency matrix, it is generated using the faces of the SMPL model. The code for that is [here](https://github.com/nkolot/GraphCMR/blob/master/utils/mesh.py). 

The adjacency matrix is not trainable. We use a shape with a fixed topology, so we kept the adjacency matrix fixed. If for some reason you want to make it trainable, there are some PyTorch limitations concerning sparse tensors and thus it might not be feasible to have a trainable sparse tensor. Of course you could make it dense, but then the operations will become slower and also it will consume significantly more memory.
