### ISSUE TITLE
Provide code (not data) for Human3.6m + SMPL training

### ISSUE THREAD

**Issue by benjiebob** [nkolot/GraphCMR#15]
Hi there, great job!

Although I'm aware that obtaining the corresponding SMPL parameters for Human3.6m is now beyond the license, it would be super useful if the code for training on these parameters were still available.

I'm in a fortunate position that I had them saved before they were taken down so want to be able to train directly on them, but more broadly, other users may wish to implement their own MOSH procedure to generate these parameters in order to reproduce the results.

I'm looking at the code you've used for Unite the People as a template but if you could provide the Human3.6m code that would be awesome.

Thanks,
Ben

**Comment by nkolot** [comment]
The code for training is already available on this repo. You just need to choose the FullDataset in the command line options.
We include code to prepare the test data of Human3.6M for evaluation. You can use this code to create the .npz file for the train data with only trivial modifications. You will need though to manually add the SMPL betas and shape parameters in the npz file. Our dataset class should be able to handle all that with no changes.

**Comment by benjiebob** [comment]
That's great thanks -- I'll close issue for now :)

**Comment by benjiebob** [comment]
I'm not sure this is quite trivial yet... The version of SMPL parameters I have contains a series of pkl files named <action>_cam<id>_aligned.pkl. In these files there is a 'new_poses' and 'betas' entry.

I'm struggling at present to get my SMPL renders to line up with the 3D key-points from S24 which originally come from 'D3_Positions_mono'. 

<img width="193" alt="Screenshot 2019-07-26 at 16 32 23" src="https://user-images.githubusercontent.com/17785299/61963329-3f7ab280-afc3-11e9-863d-702a2dbeea45.png">

I wonder if you have any tips on getting this to work?

**Comment by nkolot** [comment]
Did you try to align them? E.g. subtract the 3D location of the same joint for the 2 sets of joints? This should remove any spatial offset.

**Comment by benjiebob** [comment]
That would work in theory, although (as far as I know) your code only expects a set of shape & pose parameters for SMPL... I wouldn't be able to provide these offsets downstream?

**Comment by nkolot** [comment]
This is the standard process used in most implementations. We do not explicitly regress depth or the precise translation of the object in the camera coordinate system. In the training and evaluation code as you can see, I align them at the root joint. So it should work as intended with the pose and beta parameters we have.

**Comment by benjiebob** [comment]
I see... In this case, does it not matter that the 3D joints generated by the SMPL model (via shape + pose) align with the 3D key points from S24 (via D3_positions_mono) in the preprocessing script?

**Comment by nkolot** [comment]
Yes it does not matter. But you might have to check [this](https://github.com/nkolot/GraphCMR/issues/6) issue, where they had to reflect the pose.

**Comment by benjiebob** [comment]
Thanks so much for the help, and the tip about the 'upside-down' people. I'll close the issue again and train tonight.

**Comment by benjiebob** [comment]
As a very brief final question... is it strange that I can't see any 2D positions marked on the Human3.6m images when I view in tensorboard? It was this that began my debugging exercise -- I assumed I had them positioned incorrectly.

<img width="349" alt="Screenshot 2019-07-26 at 20 20 31" src="https://user-images.githubusercontent.com/17785299/61976138-e1f65e00-afe2-11e9-97b6-9362683364d5.png">

**Comment by geopavlakos** [comment]
You should also populate the training .npz files with the correct 2D joints. This is probably why you can't see the 2D locations here.
Also, for the SMPL parameters, you can confirm that they are correct by generating the mesh and projecting it to the image. Then you can easily evaluate the alignment between the model and the image.

**Comment by NewCoderQ** [comment]
Hi @nkolot  , what is the different processing between *.pkl and the *_camx_aligned.pkl, or could you tell me where I can find the process scripts? I want to get the continuous smpl mesh.

**Comment by LeoJoy39** [comment]
> Hi @nkolot , what is the different processing between *.pkl and the *_camx_aligned.pkl, or could you tell me where I can find the process scripts? I want to get the continuous smpl mesh.

Hello, have you found the process scripts to get the continuous smpl mash?
