### ISSUE TITLE
There is a dangerous inplace operation in SMPL()

### ISSUE THREAD

**Issue by Maqingyang** [nkolot/GraphCMR#19]
I carefully read your code, and found a dangerous inplace operation, which may lead to Runtime Error.
line 87-88 in models.smpl.py:
```
for i in range(1, 24):
    G[:,i,:,:] = torch.matmul(G[:,self.parent[i-1],:,:], G_[:, i, :, :])
```
**G is modified inplace after matmul by G_**.

To check its correctness, I wrote the following test code:
```
device = 'cuda'
pred_theta = torch.ones([1,24,3,3], requires_grad=True).to(device)
pred_beta = torch.ones([1,10], requires_grad=True).to(device)
smpl = SMPL().to(device)

pred_vertices = smpl(pred_theta, pred_beta)

torch.sum(pred_vertices).backward()
```
And pytorch report `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation`

when I fix this error like this:
```
G_new = G.clone()   
for i in range(1, 24):
        G_new[:,i,:,:] = torch.matmul(G[:,self.parent[i-1],:,:], G_[:, i, :, :])
```
Then the test code runs without any problem.

Although I found this indeed an dangerous inplace operation, however, when I ran the training code, pytorch did't report any error! I guess maybe gradient flow is cut off somewhere, so it did't need to BP through SMPL(). But this explanation sounds contradicts with the optimization process.

How do you think? Is this inplace operation a real problem? If not, how do you manage to neglect it without causing any problem?

**Comment by nkolot** [comment]
Yes this is a bug that I probably introduced when refactoring the code for release. I will fix it today.

**Comment by nkolot** [comment]
Should be ok now.

**Comment by Maqingyang** [comment]
Thanks!
