### ISSUE TITLE
About the training dataset of Human36M

### ISSUE THREAD

**Issue by weigq** [nkolot/GraphCMR#2]
Hi, thanks for the great work.
About `Due to license limitiations, we cannot provide the SMPL parameters for Human3.6M (recovered using MoSh). `, I want to know where can we download these data, and is it provided by the official Human36m dataset?

**Comment by geopavlakos** [comment]
To the best of our knowledge, this data is not available online at the moment and we are not allowed to redistribute it. We provide scripts to process the raw Human3.6M dataset and extract images and 3D joints for evaluation, but MoShed data is not provided by the original dataset.

**Comment by weigq** [comment]
Thanks, BTW, is this data obtained from [Pytorch_HMR](https://github.com/MandyMo/pytorch_HMR)?
I have already downloaded before, if so.

**Comment by geopavlakos** [comment]
We used the same training data as the original HMR approach for Human3.6M.
Although I haven't checked, I assume the PyTorch implementation was using the same data.

**Comment by weigq** [comment]
Thanks, 
I am confused where the moshed Human36m data is generated,  the author of Pytorch_HMR said it is obtained by Michael. J. Black. (https://github.com/MandyMo/pytorch_HMR/issues/18#issuecomment-476942024), but i can not find any referenced paper?

**Comment by nkolot** [comment]
https://ps.is.tuebingen.mpg.de/research_projects/mosh

**Comment by weigq** [comment]
@nkolot 
Thank you.
