### ISSUE TITLE
About test performance

### ISSUE THREAD

**Issue by zhaoyang10** [nkolot/GraphCMR#22]
Hello, 
     Thank you for releasing your great work. It helps a lot.

     But I have a little trouble in retraining the model.
     I added human3.6m dataset and set hyperparamters as paper reported, and trained the model from scratch. However, I can only get the Reconstruction Error in about 100 mm.

     I wonder whether there are some special tricks used in training procedure?

    Thanks!

**Comment by zhaoyang10** [comment]
These are losses and training renders.
![image](https://user-images.githubusercontent.com/10057534/63206067-84849700-c0e0-11e9-97b8-c04edaae46b1.png)
![epoch385_1410_nonparam_rend_cv2](https://user-images.githubusercontent.com/10057534/63206079-a8e07380-c0e0-11e9-9a84-13245a718e79.jpg)
![epoch383_1410_nonparam_rend_cv2](https://user-images.githubusercontent.com/10057534/63206080-a8e07380-c0e0-11e9-9341-e046393916da.jpg)
![epoch384_1410_nonparam_rend_cv2](https://user-images.githubusercontent.com/10057534/63206081-a8e07380-c0e0-11e9-88b3-b4a0c8224cfe.jpg)

**Comment by nkolot** [comment]
We did not use any special tricks. I can see from the plots that the camera scale and ty are the same in all images. I've seen this collapse happen a few times, and when this happens I restarted the training and it worked. Usually you can see if this is the case in the first few thousand iterations. Can you try that?

**Comment by zhaoyang10** [comment]
Thanks for replying.
'Restart' means resuming or start for epoch 1?

**Comment by nkolot** [comment]
Start training from scratch.
Can you try to finetune one of the pretrained models? If something is wrong with the data then the metrics should start to become worse.

**Comment by zhaoyang10** [comment]
I use h36m and up3d to train the vertices part (  graph_cnn.gc + graph_cnn.shape ), it seems well.

Then fix the parameters, train the camera part ( graph_cnn.camera ) several times, it always collapses to around (0.85, 0.001, 0.2).

**Comment by zhaoyang10** [comment]
> Start training from scratch.
> Can you try to finetune one of the pretrained models? If something is wrong with the data then the metrics should start to become worse.

Thanks for replying, I will try the pretrained model today.
