### ISSUE TITLE
demo img resolution

### ISSUE THREAD

**Issue by lircsszz** [nkolot/GraphCMR#23]
Hi, I`m wondering can I change the output Img size? I know the training part use 224*224 img , but in the demo file , after rendering,  I resize the img to (720,720) but it still show a 224*224 image, with pink 3D model on it.The input img is the capture from a web cam, which res is 1280 * 720

**Comment by nkolot** [comment]
So if you look at the rendering code here
```
img_gcnn = renderer.render(pred_vertices, mesh.faces.cpu().numpy(),
                           camera_t=camera_translation,
                           img=img, use_bg=True, body_color='pink')
```
The thing you have to do is replace img with your original image, and also set focal_length=5000*orig_size/224. This will do the job.
