### ISSUE TITLE
opendr?

### ISSUE THREAD

**Issue by angechen** [nkolot/GraphCMR#25]
When I convert the python version to python3 on Ubuntu, I cannot install opendr, but when I convert the python version to python2, I cannot install the other dependencies?

**Comment by nkolot** [comment]
OpenDR does not have a Python3 version. All the dependencies should be installable in Python2. We also supply a docker image with everything preinstalled. If you absolutely want to use Python3 you can use the renderer we provide in a more recent [repo](https://github.com/nkolot/SPIN)

**Comment by angechen** [comment]
Now I am using a python3 environment, I have installed all the dependencies in the requirements.txt except opendr.
You said"If you absolutely want to use Python3 you can use the renderer we provide in a more recent repo."
I don't know how to use this renderer.Can you show me some details?

**Comment by nkolot** [comment]
You can take a look [here](https://github.com/nkolot/SPIN/blob/master/train/trainer.py) where I have an example of how to use it.
