### ISSUE TITLE
How to assign the correspoding vertices of smpl with respect to skeleton points?

### ISSUE THREAD

**Issue by Maqingyang** [nkolot/GraphCMR#29]
I noted that you assigned different vertices of smpl in different datasets. And there is some mismatches of these assignments. 
For example,  when I used the ground-truth moshed parameters of Human3.6m to generate smpl model, and use JOINT_REGRESSOR_TRAIN_EXTRA to regress 3d skeleton points, the MPJPE is quite high, about 32 mm. 
So I want to re-assign these vertices to better evaluate your great work. If this is done, I am willing to attach the new joint regressor to this repo. But I am a little unfamiliar with how this assignment process are done. Could you kindly help me out here which tool I need to assign these vertices in smpl?

**Comment by geopavlakos** [comment]
If you are interested in Human3.6M in particular, you can use the definition of joints in JOINT_REGRESSOR_H36M, which are specifically estimated to reflect the Human3.6M set of joints.

**Comment by Maqingyang** [comment]
Thank you! I will try this regressor.
Furthermore, I may utilize a new dataset, MPI_INF_3DHP,  to train the model. This dataset has labeled the keypoints of human toes and endpoints of hands. It may need some tools to generate a new regressor. It there any good advice?

**Comment by geopavlakos** [comment]
For this kind of locations (i.e., landmarks on the surface instead of joints in the interior of the body) it should be pretty easy to establish correspondence by manually selecting a vertex of the mesh. For the SMPL topology, the correspondences for some of the toes and hand endpoints have already been defined [here](https://github.com/vchoutas/smplx/blob/master/smplx/vertex_ids.py).

**Comment by Maqingyang** [comment]
Thank you very very much!
It seems that this file contains corresspondences of SMPL-H and SMPL-X. Are SMPL corresspondences the same as one of them?

**Comment by geopavlakos** [comment]
SMPL and SMPL+H share the same topology, so you can use the correspondences from SMPL+H.

**Comment by Maqingyang** [comment]
I will try it now！
