### ISSUE TITLE
Can you provide datasets/extras/h36m_valid_protocol1.npz?

### ISSUE THREAD

**Issue by wei-mao-2019** [nkolot/GraphCMR#3]
Hi Nikos,

Thank you for sharing your code.

I tried to run the evaluation code but missing datasets/extras/h36m_valid_protocol1.npz. Can you provide that file?

Thank you
Cheers
Wei

**Comment by nkolot** [comment]
We provide detailed instructions on how to download and preprocess the datasets [here](https://github.com/nkolot/GraphCMR/blob/master/datasets/preprocess/README.md).

**Comment by weigq** [comment]
@nkolot 
seems that the `preprocess_datasets.py` file is not uploaded.

**Comment by nkolot** [comment]
Fixed.
