### ISSUE TITLE
How to train model with human3.6m datasets

### ISSUE THREAD

**Issue by RanFeng** [nkolot/GraphCMR#30]
Good job!
I want to train this model with human3.6m datasets, Could you please let me know how to go with it ?
Thanks!!

**Comment by geopavlakos** [comment]
In our training, we use pseudo ground truth SMPL pose and shape parameters (generated by MoSh) to train on Human3.6M. Unfortunately, due to license agreement of the dataset, we are not allowed to distribute this data.
