### ISSUE TITLE
Preprocess of ground truth keypoints_3d on Human3.6M

### ISSUE THREAD

**Issue by yuxwind** [nkolot/GraphCMR#31]
I tried to generate pseudo_keypoints_3d from the ground truth SMPL parameters of the Human3.6M dataset using smpl.get_joints(). I hope it can be consistent with the ground truth keypoints_3d. But I noticed that the MPJPE can be more than 0.2m without subtracting the pelvis(root). And the MPJPE is about 0.03m when subtracting the pelvis. 

Here is a figure to show the distance between the joints of gt_keypoints_3d(in red) and pseudo_keypoints_3d(in blue):

![test](https://user-images.githubusercontent.com/5462068/68090612-a53ccd00-fe43-11e9-8b92-5a31144db5da.png)

As the pred_pelvis and gt_pelvis are subtracted from the predicted_keypoints_3d and gt_keypoints_3d separately for the loss, I guess it doesn't matter if I don't preprocess gt_keypoints_3d and gt_smpl_paramteres to make them consistent. 

Did you preprocess them? If you did, how did you do that? Thanks!

**Comment by geopavlakos** [comment]
The ground truth 3D keypoints we use are coming directly from the annotations of Human3.6M, where the only preprocessing we do is to subtract the pelvis joint. The 3D keypoints generated by SMPL parameters, no matter how accurate these parameters are, cannot exactly replicate the 3D keypoints that the dataset provides.
