### ISSUE TITLE
questions about "mesh_downsampling.npz"

### ISSUE THREAD

**Issue by moondabaojian** [nkolot/GraphCMR#33]
I want know how to compute mesh_downsampling.npz("Extra file with precomputed downsampling for the SMPL body mesh." )
Can you provide code about it ? Thank you !

**Comment by nkolot** [comment]
It was computed using the algorithm from [this](https://github.com/anuragranj/coma) paper. You can look at [this](https://github.com/anuragranj/coma/blob/master/lib/coarsening.py) file for more details.
