### ISSUE TITLE
Regarding fully connected baseline

### ISSUE THREAD

**Issue by mehtadushy** [nkolot/GraphCMR#34]
Hi

I was unable to find the details for the fully connected mesh regression baseline in the paper. Will you make the code for it available such that the baseline can be further examined?

**Comment by nkolot** [comment]
Here is the code we used for the baseline.

```
class BaselineModel(nn.Module):
    
    def __init__(self, ref_vertices):
        super(BaselineModel, self).__init__()
        self.ref_vertices = ref_vertices
        self.resnet = resnet50(pretrained=True)
        self.shape = nn.Sequential(FCBlock(2048, 2048),
                                   nn.Linear(2048, self.ref_vertices.shape[0] * 3))
        self.camera_fc = nn.Sequential(FCBlock(2048, 1024),
                                      nn.Linear(1024, 3))

    def forward(self, image):
        image_enc = self.resnet(image)
        shape = self.shape(image_enc)
        shape = shape.view(-1, 3, self.ref_vertices.shape[0])
        cam = self.camera_fc(image_enc)
        return shape, cam
```

**Comment by mehtadushy** [comment]
Hi

Another follow up on this. Do you think this is a fair baseline considering it only has 2 layers and 1 nonlinearity while the GraphCNN has multiple (15-20 ?) layers + access to additional information through the mesh? Or am I missing something?

**Comment by nkolot** [comment]
Indeed the fully connected baseline is not as deep as the GraphCNN, but for our comparison we took into consideration the number of parameters. For the shape regression, the FC baseline includes about 15 million parameters (2048*2048 + 2048 * (6890/4) * 3), compared to about 2.5 million parameters for our Graph-CNN ( 2051*512 + 5 blocks * (512*256+256*256+256*512)  + 64*32 + 32*3). You can make the fully connected baseline deeper, but this would come with the cost of significantly increasing the number of required parameters.

**Comment by mehtadushy** [comment]
Yes, but the number of parameters is not the same as representational capacity, and number of parameters is not the same as computational cost (and inference time) either. FC layers, despite their huge number of parameters, have a significantly smaller compute cost than, say, convolution layers operating on 2D grids. Further, there exist many ways to trivially or non-trivially compress fully-connected networks, which makes the number of parameters argument moot.  

In my opinion, and perhaps you and others would agree, the baselines should be comparable in terms of representational capacity / inference time / compute cost to be meaningful.
