### ISSUE TITLE
where is preprocess_datasets.py?

### ISSUE THREAD

**Issue by mehameha998** [nkolot/GraphCMR#4]

**Comment by nkolot** [comment]
Fixed.

**Comment by mehameha998** [comment]
Thanks!

**Comment by mehameha998** [comment]
@nkolot , sooorry bother you again. json file seems also missed. Could you please upload them?

**Comment by nkolot** [comment]
Sorry for that, I fixed it. The config.json I added in the folder data is essentially the same config file that  the training code automatically dumps when you start training.
