### ISSUE TITLE
Training parameters?

### ISSUE THREAD

**Issue by mehameha998** [nkolot/GraphCMR#6]
Hi @nkolot , I have run your code. I found it can work without Human 3.6M data. Once I add Human3.6 M data into training set, GraphCMR seems cannot converge. 
My setting is batch_size=32, shffule_train=True, and others is exactly same as[ config.py](https://github.com/nkolot/GraphCMR/blob/master/config.py). By the way, my human3.6M data includes Moshed-annotations. 
Could you tell me your training configuration?

**Comment by mehameha998** [comment]
Forgot mention it, I trained GraphCMR from the scratch.

**Comment by nkolot** [comment]
I've tested batch_size=32 before and it gives slightly better results than the ones reported in the paper.
What do you mean by it fails to converge? For how many iterations did you train?
From my experience, you should start seeing reasonable results at around 10k iterations. In the very early stages of training you will not see shapes at all.
As a debugging tip, try to resume training from one of the checkpoints I provided. If there is something wrong with the data format, probably the training will collapse.
Also it would be helpful if you sent me a few screenshots from Tensorboard to tell you if there is sth wrong.

**Comment by mehameha998** [comment]
I figure out the problem. I didn't notice that I should reflect pose, as posted in this [issue](https://github.com/akanazawa/hmr/issues/50).  After fixing this bug, I retried training GraphCMR model for 7500 iterations. Much better than before results!  Sorry for this mistake.
